#!/usr/bin/env bash
# Rebuild the working data from public sources.
#
# The repo intentionally ships no corpus (we do not republish newspaper content), but
# every piece is reconstructible. This script fetches what is public and derives the rest.
# After it runs, the only thing still missing is clue TEXT and grid geometry, which come
# from vision-transcribing the puzzle images — step 6, which an agent does itself.
#
#   ./bootstrap.sh            # everything scriptable
#   ./bootstrap.sh --dev-only # images for the 4 dev puzzles only (cheap; enough to evaluate)
#
# Sources, all public:
#   hspell wordlist   github.com/eyaler/hebrew_wordlists
#   answers corpus    14across.co.il          (plain HTTP, no login)
#   culture entities  he.wikipedia.org API
#   puzzle images     img.haarets.co.il CDN   (public once the URL is known; the URL
#                                              manifest data/image_urls.txt is in the repo)
set -euo pipefail
cd "$(dirname "$0")"
DEV_ONLY=${1:-}

echo "==> 1/6  Hebrew lexicon (129k words)"
mkdir -p solver/lex
if [ ! -s solver/lex/hspell.txt ]; then
  curl -sL -o solver/lex/hspell.txt \
    "https://raw.githubusercontent.com/eyaler/hebrew_wordlists/main/hspell_simple.txt"
fi
wc -l < solver/lex/hspell.txt | xargs echo "    words:"

echo "==> 2/6  answers corpus from 14across (52 puzzles, ~1,450 clues)"
mkdir -p data/answers/by_date data/dataset
if [ ! -s data/answers/answers_parsed.json ]; then
  python3 - <<'PY'
import urllib.parse
base = ('https://www.14across.co.il/answers.php?crossword=16&name='
        + urllib.parse.quote('הארץ, יורם הרועה', safe=','))
d26 = "17/07 10/07 03/07 26/06 19/06 12/06 05/06 29/05 21/05 15/05 08/05 01/05 24/04 17/04 10/04 03/04 01/04 27/03 20/03 13/03 06/03 27/02 20/02 13/02 06/02 30/01 23/01 16/01 09/01 02/01".split()
d25 = "26/12 19/12 12/12 05/12 28/11 21/11 14/11 07/11 31/10 24/10 17/10 10/10 03/10 26/09 19/09 12/09 05/09 29/08 22/08 15/08 08/08 01/08".split()
urls = [f'{base}&date={d}/2026' for d in d26] + [f'{base}&date={d}/2025' for d in d25]
open('data/answer_urls.txt', 'w').write('\n'.join(urls) + '\n')
print(f'    staged {len(urls)} answer pages')
PY
  python3 scraper/parse_answers.py
fi
python3 - <<'PY'
import json, os
d = json.load(open('data/answers/answers_parsed.json'))
os.makedirs('data/answers/by_date', exist_ok=True)
for p in d:
    dd, mm, yy = p['puzzle_date'].split('/')
    json.dump(p, open(f'data/answers/by_date/{yy}-{mm}-{dd}.json', 'w'), ensure_ascii=False, indent=1)
print(f"    {len(d)} puzzles, {sum(len(p['clues']) for p in d)} clues")
PY

echo "==> 3/6  culture entities from he-wikipedia"
[ -s solver/lex/culture.json ] || python3 scraper/harvest_culture.py

echo "==> 4/6  substitution dictionary (derived from the explanations)"
python3 solver/substitutions.py build | head -3

echo "==> 5/6  puzzle images from the public CDN"
mkdir -p data/images
DEV_DATES="2026-06-04 2026-05-28 2026-05-20 2026-05-14"   # article dates for the 4 dev puzzles
while IFS='|' read -r d p; do
  [ -z "${d:-}" ] && continue
  if [ "$DEV_ONLY" = "--dev-only" ]; then
    case " $DEV_DATES " in *" $d "*) ;; *) continue ;; esac
  fi
  f="data/images/${d}.jpg"
  [ -s "$f" ] && continue
  curl -s -o "$f" "https://img.haarets.co.il${p}?&width=1500&height=1980&cmsprod"
  sleep 0.4
done < data/image_urls.txt
echo "    images: $(ls data/images 2>/dev/null | wc -l | xargs)"

echo "==> 6/6  clue text + grids  [AGENT STEP — not scriptable]"
cat <<'NOTE'
    Clue text and grid geometry are not in the repo and cannot be downloaded: they must be
    read off the images. To rebuild them for a puzzle:

      a) Read data/images/<article-date>.jpg. Find the section titled תשבץ היגיון by
         יורם הרועה (ignore the other crossword on the page). Transcribe every clue:
         number, direction (אופקי=across, אנכי=down), full Hebrew text, and the trailing
         enumeration in parentheses.
      b) VALIDATE: sum(enum) must equal the answer's Hebrew letter count from
         data/answers/by_date/<puzzle-date>.json. Beware REVERSED enumerations — 6 of 50
         puzzles printed them in visual rather than word order. solver/fix_enums.py detects this.
      c) Grid: transcribe the black/white pattern (11 wide x 15 tall), row 0 top, string
         index 0 = RIGHTMOST cell (RTL). Then run:
           python3 solver/grid_tools.py validate data/grids/<date>.json data/dataset/inputs/<date>.json
         It recomputes the numbering and must print OK. Grids for the dev/eval puzzles are
         already committed, so this is only needed for a NEW puzzle.
      d) Write data/clues/<puzzle-date>.json then run: python3 solver/build_dataset.py

    Note the article date and the puzzle date differ (the paper dates the puzzle to the
    following day). data/pairing.json is regenerated by build_dataset.py.
NOTE

echo
echo "Bootstrap done. If data/dataset/clues.jsonl exists you can evaluate:"
echo "  python3 evals/run_eval.py <solutions.json>"
