#!/usr/bin/env python3
"""Definition-fit scoring for candidates already generated by candidates.py.

WHY (RESULTS.md/DAILY.md queue item 9, "the sharpest gap PR #24 surfaced"): this
project's only two live solve trials landed at 1/4 = 25% precision, and BOTH misses
were prove.py correctly verifying a REAL mechanism (the letters genuinely anagram,
the reversal genuinely works) on a candidate that simply does not mean what the clue
defines. The proof gate checks whether the wordplay executes; nothing in the pipeline
checks whether the result FITS THE DEFINITION. candidates.py hands back up to max_n
candidates per clue in a fixed mechanism-priority order (homograph/substitution first,
then the cheap window-scan mechanisms) with no notion of which one is more likely to
be the setter's intended answer.

A prior attempt at an adjacent problem — defspan.py's definition-SPAN detection,
locating WHICH END of the clue holds the definition — was tried and measured negative
(DAILY.md 2026-08-19): most clues here carry no indicator word to key off, so a
location classifier degenerates to a fixed default. DAILY.md is explicit that this
item should not be re-attempted "without a fundamentally different signal." This
module deliberately uses a different one: instead of finding WHERE in the clue the
definition sits, it asks whether the CANDIDATE ANSWER's own known meaning (mined from
the same private_defs/train-explanation corpus solver/retrieve_defs.py already
indexes for retrieval_candidates) overlaps the clue's FULL surface text. No span
localization is attempted at all — a candidate with a well-attested definition that
shares vocabulary with the clue scores high; a mechanically-real but semantically
unrelated candidate scores zero, because nothing in the corpus was ever written to
define it that way.

This is deliberately NOT a new candidate generator: it never proposes an answer that
wasn't already in candidates.generate()'s output. It only RE-RANKS what's already
there, so it can never inflate recall@N (measured unchanged by construction — see
selftest) and can only be judged on whether it moves the gold answer higher in the
list when the gold answer is already present. That is the honest, narrow claim to
measure: does definition-fit reranking make the FIRST candidate more likely to be
correct, which is what a live solve pass actually commits.

CLI:
  python3 solver/deffit.py clue "<text>" <enum...>            # ranked, with def_fit scores
  python3 solver/deffit.py eval data/dataset/clues.jsonl eval   # rerank quality, conditional on recall
  python3 solver/deffit.py selftest
"""
import sys, os, json, math
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)


def _mods():
    import candidates, retrieve_defs
    return candidates, retrieve_defs


def build_answer_index(docs_df=None):
    """Reverses retrieve_defs.build_index()'s (tokens, answers, pid) docs into
    answer -> [doc tokens]. Same held-out-safe corpus retrieval_candidates already
    uses (private_defs is unconditionally external; train-split explanations exclude
    every dev/eval answer via retrieve_defs.held_out()) — no new filtering needed
    here, because this module never returns an answer that wasn't already a
    candidates.py hit; it only scores answers candidates.py already vetted as
    mechanically POSSIBLE."""
    _, retrieve_defs = _mods()
    cwd = os.getcwd()
    try:
        os.chdir(ROOT)
        docs, df = docs_df if docs_df is not None else retrieve_defs.build_index()
    finally:
        os.chdir(cwd)
    N = len(docs)
    avg = sum(len(t) for t, _, _ in docs) / max(N, 1)
    ans_docs = defaultdict(list)
    for toks, answers, _pid in docs:
        for a in answers:
            ans_docs[a].append(toks)
    return {'N': N, 'df': df, 'avg': avg, 'ans_docs': ans_docs}


def _bm25_query_doc(q_toks, doc_toks, N, df, avg):
    """Identical scoring formula to retrieve_defs.candidates()'s per-doc term, so a
    def_fit score is directly comparable to the score retrieval_candidates() already
    surfaces — this module reuses the corpus's own validated ranking function rather
    than inventing a second one."""
    tl = len(doc_toks) or 1
    s = 0.0
    for w in q_toks:
        tf = doc_toks.count(w)
        if not tf:
            continue
        idf = math.log(1 + (N - df.get(w, 0) + .5) / (df.get(w, 0) + .5))
        s += idf * tf * 2.2 / (tf + 1.2 * (0.25 + 0.75 * tl / avg))
    return s


def def_fit_score(clue_text, answer, idx):
    """0.0 means 'no known definition for this answer in the corpus', NOT 'known
    to be a bad fit' — most candidates (rare names, coined multi-word answers) will
    score 0.0 simply because nothing in a modest corpus defines them. This is why
    reranking uses a STABLE sort (see rerank()): zero-evidence candidates keep their
    original mechanism-priority order rather than being shuffled arbitrarily."""
    _, retrieve_defs = _mods()
    q = set(retrieve_defs.toks(clue_text))
    docs = idx['ans_docs'].get(answer)
    if not docs:
        return 0.0
    return max(_bm25_query_doc(q, t, idx['N'], idx['df'], idx['avg']) for t in docs)


def rerank(clue_text, cands, idx):
    """Stable-sorts candidates by def_fit score, descending; ties (including the
    common 0.0-vs-0.0 case) preserve candidates.py's own mechanism-priority order.
    Returns NEW dicts (each carries a 'def_fit' key); never mutates the input or
    drops/adds a candidate, so recall@N over the result is identical to recall@N
    over the input by construction."""
    scored = [(def_fit_score(clue_text, c['answer'], idx), i, c) for i, c in enumerate(cands)]
    scored.sort(key=lambda x: (-x[0], x[1]))
    out = []
    for score, _i, c in scored:
        c2 = dict(c)
        c2['def_fit'] = score
        out.append(c2)
    return out


# ---------------------------------------------------------------------------
def eval_rerank(dataset_path, split=None, max_n=25, idx=None):
    """Reranking quality, CONDITIONAL on the gold answer already being present in
    candidates.generate()'s output (i.e. conditional on a recall@N hit) — this is
    the honest way to isolate what reranking can possibly contribute, since it can
    never rescue a clue candidates.py never generated the answer for at all. Reports
    top-1 accuracy and mean reciprocal rank (MRR) before vs after, on the exact same
    hit set both times, so any movement is attributable to reranking alone."""
    candidates, _ = _mods()
    idx = idx if idx is not None else build_answer_index()
    total = 0
    recall_hit = 0
    base_top1 = base_rr = rerank_top1 = rerank_rr = 0
    moved_up = moved_down = unchanged = 0
    examples = []
    for line in open(dataset_path):
        r = json.loads(line)
        if split and r.get('split') != split:
            continue
        if not r.get('answer_raw'):
            continue
        total += 1
        cands = candidates.generate(r['clue_text'], r['enum'], max_n=max_n)
        gold = candidates.norm(r['answer_raw'])
        base_rank = next((i + 1 for i, c in enumerate(cands) if c['answer'] == gold), None)
        if base_rank is None:
            continue
        recall_hit += 1
        reranked = rerank(r['clue_text'], cands, idx)
        re_rank = next((i + 1 for i, c in enumerate(reranked) if c['answer'] == gold), None)
        base_top1 += base_rank == 1
        rerank_top1 += re_rank == 1
        base_rr += 1.0 / base_rank
        rerank_rr += 1.0 / re_rank
        if re_rank < base_rank:
            moved_up += 1
        elif re_rank > base_rank:
            moved_down += 1
        else:
            unchanged += 1
        examples.append((r['clue_number'], r['direction'], gold, base_rank, re_rank))
    return {
        'total': total, 'recall_hit': recall_hit,
        'base_top1': base_top1, 'rerank_top1': rerank_top1,
        'base_mrr': base_rr / recall_hit if recall_hit else 0.0,
        'rerank_mrr': rerank_rr / recall_hit if recall_hit else 0.0,
        'moved_up': moved_up, 'moved_down': moved_down, 'unchanged': unchanged,
        'examples': examples,
    }


# ---------------------------------------------------------------------------
def selftest():
    """Synthetic corpus, modelled on retrieve_defs.py/candidates.py's own selftests
    (an injected idx, never the real corpus) — this file must never be able to pass
    its own selftest by accidentally scoring a real dev/eval answer."""
    ok = True

    print('--- def_fit_score: a candidate with an attested, overlapping definition '
          'scores above one with none ---')
    docs = [
        (['נשיא', 'ראשון', 'מדינת', 'ישראל'], [], None),  # tokens only matter per-answer below
    ]
    # build_answer_index() expects (tokens, answers, pid) triples; construct directly
    # rather than going through retrieve_defs.build_index(), same discipline as
    # candidates.py's injectable docs_df.
    N = 2
    df = {'נשיא': 1, 'ראשון': 1, 'מדינת': 1, 'ישראל': 1, 'פרח': 1, 'לאומי': 1}
    ans_docs = {
        'וייצמן': [['נשיא', 'ראשון', 'מדינת', 'ישראל']],
        'כלנית': [['פרח', 'לאומי']],
    }
    idx = {'N': N, 'df': df, 'avg': 4, 'ans_docs': ans_docs}
    s_hit = def_fit_score('מי היה הנשיא הראשון של המדינה', 'וייצמן', idx)
    s_unknown = def_fit_score('מי היה הנשיא הראשון של המדינה', 'תפוח', idx)
    print(f'  attested candidate score {s_hit:.2f} > unknown-answer score {s_unknown:.2f}: '
          f'{s_hit > s_unknown} (expected True)')
    ok &= s_hit > s_unknown

    print('--- def_fit_score: no known definition for an answer scores exactly 0.0 ---')
    s = def_fit_score('משהו לגמרי לא קשור', 'תפוח', idx)
    print(f'  score: {s} (expected 0.0)')
    ok &= s == 0.0

    print('--- rerank: promotes a buried-but-attested candidate to first place ---')
    cands = [
        {'answer': 'תפוח', 'mechanism': 'anagram', 'fodder': 'x'},
        {'answer': 'לחם', 'mechanism': 'hidden', 'fodder': 'y'},
        {'answer': 'וייצמן', 'mechanism': 'pattern', 'fodder': 'z'},  # correct, but last
    ]
    out = rerank('מי היה הנשיא הראשון של המדינה', cands, idx)
    print(f'  first candidate after rerank: {out[0]["answer"]} (expected וייצמן)')
    ok &= out[0]['answer'] == 'וייצמן'
    print(f'  def_fit key attached to every candidate: '
          f'{all("def_fit" in c for c in out)} (expected True)')
    ok &= all('def_fit' in c for c in out)

    print('--- rerank: never drops or adds a candidate (recall@N is unchanged) ---')
    same_set = {c['answer'] for c in cands} == {c['answer'] for c in out}
    print(f'  same answer set before/after: {same_set} (expected True)')
    ok &= same_set
    print(f'  same count before/after: {len(cands) == len(out)} (expected True)')
    ok &= len(cands) == len(out)

    print('--- rerank: ties (both zero-evidence) preserve original mechanism order ---')
    cands2 = [
        {'answer': 'א', 'mechanism': 'anagram', 'fodder': None},
        {'answer': 'ב', 'mechanism': 'hidden', 'fodder': None},
    ]
    idx_empty = {'N': 1, 'df': {}, 'avg': 1, 'ans_docs': {}}
    out2 = rerank('קלמ', cands2, idx_empty)
    print(f'  order preserved: {[c["answer"] for c in out2] == ["א", "ב"]} (expected True)')
    ok &= [c['answer'] for c in out2] == ['א', 'ב']

    print(f'\n{"ALL PASSED" if ok else "FAILURES ABOVE"}')
    return ok


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return
    cmd = sys.argv[1]
    if cmd == 'selftest':
        sys.exit(0 if selftest() else 1)
    elif cmd == 'clue':
        candidates, _ = _mods()
        text = sys.argv[2]
        enum = [int(x) for x in sys.argv[3].split(',')]
        os.chdir(ROOT)
        cands = candidates.generate(text, enum)
        idx = build_answer_index()
        for c in rerank(text, cands, idx):
            print(f"[{c['def_fit']:.2f}] {c['answer']}  ({c['mechanism']}, fodder={c.get('fodder')})")
    elif cmd == 'eval':
        rest = sys.argv[2:]
        path = rest[0] if len(rest) > 0 else 'data/dataset/clues.jsonl'
        split = rest[1] if len(rest) > 1 else None
        os.chdir(ROOT)
        res = eval_rerank(path, split)
        print(f"recall_hit (gold in candidate list): {res['recall_hit']}/{res['total']}")
        print(f"top-1 accuracy, conditional on recall: "
              f"baseline {res['base_top1']}/{res['recall_hit']} "
              f"({res['base_top1']/max(res['recall_hit'],1):.1%})  ->  "
              f"reranked {res['rerank_top1']}/{res['recall_hit']} "
              f"({res['rerank_top1']/max(res['recall_hit'],1):.1%})")
        print(f"MRR: baseline {res['base_mrr']:.3f}  ->  reranked {res['rerank_mrr']:.3f}")
        print(f"moved up: {res['moved_up']}  moved down: {res['moved_down']}  "
              f"unchanged: {res['unchanged']}")
        if res['examples']:
            print('\nper-clue (number, direction, gold, base_rank, rerank_rank):')
            for num, direction, gold, br, rr in res['examples']:
                print(f'  {num} {direction}: {gold}  {br} -> {rr}')
    else:
        print(__doc__)


if __name__ == '__main__':
    main()
